package drivers

import (
	_ "github.com/kinyokun/OpenList/drivers/115"
	_ "github.com/kinyokun/OpenList/drivers/115_open"
	_ "github.com/kinyokun/OpenList/drivers/115_share"
	_ "github.com/kinyokun/OpenList/drivers/123"
	_ "github.com/kinyokun/OpenList/drivers/123_link"
	_ "github.com/kinyokun/OpenList/drivers/123_open"
	_ "github.com/kinyokun/OpenList/drivers/123_share"
	_ "github.com/kinyokun/OpenList/drivers/139"
	_ "github.com/kinyokun/OpenList/drivers/189"
	_ "github.com/kinyokun/OpenList/drivers/189pc"
	_ "github.com/kinyokun/OpenList/drivers/alias"
	_ "github.com/kinyokun/OpenList/drivers/aliyundrive"
	_ "github.com/kinyokun/OpenList/drivers/aliyundrive_open"
	_ "github.com/kinyokun/OpenList/drivers/aliyundrive_TV_open"
	_ "github.com/kinyokun/OpenList/drivers/aliyundrive_share"
	_ "github.com/kinyokun/OpenList/drivers/azure_blob"
	_ "github.com/kinyokun/OpenList/drivers/baidu_netdisk"
	_ "github.com/kinyokun/OpenList/drivers/baidu_photo"
	_ "github.com/kinyokun/OpenList/drivers/baidu_share"
	_ "github.com/kinyokun/OpenList/drivers/chaoxing"
	_ "github.com/kinyokun/OpenList/drivers/cloudreve"
	_ "github.com/kinyokun/OpenList/drivers/cloudreve_v4"
	_ "github.com/kinyokun/OpenList/drivers/crypt"
	_ "github.com/kinyokun/OpenList/drivers/doubao"
	_ "github.com/kinyokun/OpenList/drivers/doubao_share"
	_ "github.com/kinyokun/OpenList/drivers/dropbox"
	_ "github.com/kinyokun/OpenList/drivers/febbox"
	_ "github.com/kinyokun/OpenList/drivers/ftp"
	_ "github.com/kinyokun/OpenList/drivers/github"
	_ "github.com/kinyokun/OpenList/drivers/github_releases"
	_ "github.com/kinyokun/OpenList/drivers/google_drive"
	_ "github.com/kinyokun/OpenList/drivers/google_photo"
	_ "github.com/kinyokun/OpenList/drivers/halalcloud"
	_ "github.com/kinyokun/OpenList/drivers/ilanzou"
	_ "github.com/kinyokun/OpenList/drivers/ipfs_api"
	_ "github.com/kinyokun/OpenList/drivers/kodbox"
	_ "github.com/kinyokun/OpenList/drivers/lanzou"
	_ "github.com/kinyokun/OpenList/drivers/lenovonas_share"
	_ "github.com/kinyokun/OpenList/drivers/local"
	_ "github.com/kinyokun/OpenList/drivers/mediatrack"
	_ "github.com/kinyokun/OpenList/drivers/mega"
	_ "github.com/kinyokun/OpenList/drivers/misskey"
	_ "github.com/kinyokun/OpenList/drivers/mopan"
	_ "github.com/kinyokun/OpenList/drivers/netease_music"
	_ "github.com/kinyokun/OpenList/drivers/onedrive"
	_ "github.com/kinyokun/OpenList/drivers/onedrive_app"
	_ "github.com/kinyokun/OpenList/drivers/onedrive_sharelink"
	_ "github.com/kinyokun/OpenList/drivers/openlist"
	_ "github.com/kinyokun/OpenList/drivers/pikpak"
	_ "github.com/kinyokun/OpenList/drivers/pikpak_share"
	_ "github.com/kinyokun/OpenList/drivers/quark_open"
	_ "github.com/kinyokun/OpenList/drivers/quark_uc"
	_ "github.com/kinyokun/OpenList/drivers/quark_uc_tv"
	_ "github.com/kinyokun/OpenList/drivers/s3"
	_ "github.com/kinyokun/OpenList/drivers/seafile"
	_ "github.com/kinyokun/OpenList/drivers/sftp"
	_ "github.com/kinyokun/OpenList/drivers/smb"
	_ "github.com/kinyokun/OpenList/drivers/teambition"
	_ "github.com/kinyokun/OpenList/drivers/terabox"
	_ "github.com/kinyokun/OpenList/drivers/thunder"
	_ "github.com/kinyokun/OpenList/drivers/thunder_browser"
	_ "github.com/kinyokun/OpenList/drivers/thunderx"
	_ "github.com/kinyokun/OpenList/drivers/trainbit"
	_ "github.com/kinyokun/OpenList/drivers/url_tree"
	_ "github.com/kinyokun/OpenList/drivers/uss"
	_ "github.com/kinyokun/OpenList/drivers/virtual"
	_ "github.com/kinyokun/OpenList/drivers/webdav"
	_ "github.com/kinyokun/OpenList/drivers/weiyun"
	_ "github.com/kinyokun/OpenList/drivers/wopan"
	_ "github.com/kinyokun/OpenList/drivers/yandex_disk"
)

// All do nothing,just for import
// same as _ import
func All() {

}
